name: checkpoint05_webservices_rm550347
description: Um aplicativo Flutter para gerenciamento de receitas.
version: 1.0.0


environment:
  sdk: ^3.8.1


dependencies:  
  flutter:
    sdk: flutter
  http: ^1.2.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
